"""empty message

Revision ID: 1ec3d3d1acbc
Revises: 27398cb5e4fa
Create Date: 2018-05-08 10:17:31.181852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec3d3d1acbc'
down_revision = '27398cb5e4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast', sa.Column('pulses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('leg', sa.Column('pulses', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leg', 'pulses')
    op.drop_column('cast', 'pulses')
    # ### end Alembic commands ###
