"""empty message

Revision ID: 27398cb5e4fa
Revises: a2783d46b892
Create Date: 2018-05-08 09:56:56.975706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27398cb5e4fa'
down_revision = 'a2783d46b892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_count_dt', table_name='count')
    op.add_column('leg', sa.Column('time_in', sa.DateTime(), nullable=True))
    op.add_column('leg', sa.Column('time_out', sa.DateTime(), nullable=False, server_default='now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leg', 'time_out')
    op.drop_column('leg', 'time_in')
    op.create_index('ix_count_dt', 'count', ['dt'], unique=False)
    # ### end Alembic commands ###
