"""empty message

Revision ID: 6796683aaadb
Revises: 1ec3d3d1acbc
Create Date: 2018-05-11 11:45:45.638000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6796683aaadb'
down_revision = '1ec3d3d1acbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leg', sa.Column('transit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leg', 'transit')
    # ### end Alembic commands ###
