"""empty message

Revision ID: a2783d46b892
Revises: 
Create Date: 2018-05-05 12:40:18.992382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2783d46b892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast', sa.Column('cast', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast', 'cast')
    # ### end Alembic commands ###
